export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Design } from './Design'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as TabButton } from './TabButton'
export { default as Works } from './Works'

export { default as LoadingSpinner } from './ui/LoadingSpinner'
